apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-ml-dashboard
spec:
  replicas: 2  # Number of pods
  selector:
    matchLabels:
      app: streamlit-ml-dashboard
  template:
    metadata:
      labels:
        app: streamlit-ml-dashboard
    spec:
      containers:
      - name: streamlit
        image: joindevops006/joindevops:machine
        ports:
        - containerPort: 8501

---

apiVersion: v1
kind: Service
metadata:
  name: streamlit-ml-dashboard
spec:
  selector:
    app: streamlit-ml-dashboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: LoadBalancer
